apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: namespace-admin
  namespace: notes-app
rules:
  - apiGroups: ["apps"] # "" indicates the core API group
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: azure-devops:namespace-admin
  namespace: notes-app
subjects:
  # You can specify more than one "subject"
  - kind: ServiceAccount
    name: azure-devops # "name" is case sensitive
    namespace: notes-app
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: Role #this must be Role or ClusterRole
  name: namespace-admin # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io
