apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: terraform.io:cluster-admin
  namespace: notes-app
subjects:
  # You can specify more than one "subject"
  - kind: ServiceAccount
    name: terraform.io # "name" is case sensitive
    namespace: kube-system
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: ClusterRole #this must be Role or ClusterRole
  name: cluster-admin # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io
